argos-ci/argos-javascript

package-lock.json
packages/argos-cli/package.json
packages/argos-cli/src/cancel.js
packages/argos-cli/src/getEnvironment.js
packages/argos-cli/src/getEnvironment.test.js
packages/argos-cli/src/upload.js

Support all must known CI services: https://github.com/semantic-release/env-ci\#supported-ci

feat(cli): automatic variable detection for CI providers

---

packages/core/src/api-client.ts
packages/core/src/upload.ts

- feat(core): improve errors
- fix(upload): handle same screenshots

various fixes

---

packages/core/src/ci-environment/services/github-actions.ts

docs(core): clarify commit detection error

---

packages/cli/src/index.ts
packages/core/src/api-client.ts
packages/core/src/ci-environment/index.ts
packages/core/src/ci-environment/services/buildkite.ts
packages/core/src/ci-environment/services/circleci.ts
packages/core/src/ci-environment/services/github-actions.ts
packages/core/src/ci-environment/services/heroku.ts
packages/core/src/ci-environment/services/travis.ts
packages/core/src/ci-environment/types.ts
packages/core/src/config.test.ts
packages/core/src/config.ts
packages/core/src/upload.ts

feat: get PR numbers

---

packages/core/src/debug.ts
packages/core/src/upload.ts
packages/core/src/util/chunk.ts

To avoid overloading the network.

feat(core): split upload in chunks

---

.prettierignore
README.md

https://github.com/argos-ci/argos-ci.com/issues/74

feat(discord): update link

---

packages/browser/src/stabilization.ts

It has to be synchronous, not asynchronous.

fix(stabilization): fix stabilization function

---

packages/cypress/docs/index.mdx
packages/cypress/package.json

Make types available in npm package and add documentation about it.

fix(cypress): fix typescript

---

build/rollup.js
package.json
packages/browser/package.json
packages/browser/rollup.config.js
packages/browser/src/cypress.ts
packages/cypress/src/support.ts
pnpm-lock.yaml
tsconfig.json

Fix https://github.com/argos-ci/argos/issues/1126
- Inline version
- Rely on cjs to resolve path

fix(cypress): improve compatibility with bundlers

---

packages/core/src/ci-environment/services/github-actions.ts

Fix wrong pull request set while running from a "deployment_status" event.

fix(github): fix running from "deployment_status"

---

packages/cypress/docs/index.mdx
packages/playwright/docs/index.mdx

- docs(playwright): improve documentation
- docs(cypress): use title code block

improve docs

---

packages/browser/src/global/stabilization.ts
packages/cypress/src/support.ts
packages/playwright/docs/index.mdx
packages/playwright/src/index.ts
packages/puppeteer/docs/index.mdx
packages/puppeteer/src/index.ts

- refactor: remove unused exports
- feat(playwright): add `disableHover` option by default
- refactor(cypress): align with Playwright code
- feat(puppeteer): add `disableHover` option by default

110 enhance hover stabilization

---

packages/browser/src/global/stabilization.ts

See https://github.com/facebook/docusaurus/pull/9875 for context.

feat(stability): handle img with decoding="async"

---

packages/core/package.json
packages/core/src/discovery.ts
packages/playwright/e2e.spec.ts
packages/playwright/package.json
packages/playwright/src/debug.ts
packages/playwright/src/index.ts
packages/playwright/src/reporter.ts
packages/webdriverio/package.json
pnpm-lock.yaml

- **fix(playwright): prepend the project name in the screenshot name**
- **chore: add debug mode**

various fixes playwright

---

packages/browser/src/global/stabilization.ts

This PR improves the stabilization of navigation elements in Argos JavaScript. The main goal is to make the positioning stabilization safer.
- **Safer Positioning Stabilization**: Enhanced handling of sticky and fixed navigation elements to prevent discrepancies during visual testing.
- **Improved Element Handling**: Previously, this stabilization could create issues with other elements like popovers. With this update, such conflicts should be resolved.
- Utilizes `getBoundingClientRect` to compare positions. If the `x` and `y` coordinates are the same, the position is considered safe. 
With these changes, Argos JavaScript now offers more reliable visual testing, ensuring a smoother experience for developers.

fix(stabilization): safer positionning stabilization

---

packages/cli/src/index.ts
packages/core/src/api-client.test.ts
packages/core/src/api-client.ts
packages/core/src/ci-environment/index.ts
packages/core/src/ci-environment/services/bitrise.ts
packages/core/src/ci-environment/services/buildkite.ts
packages/core/src/ci-environment/services/circleci.ts
packages/core/src/ci-environment/services/git.ts
packages/core/src/ci-environment/services/github-actions.ts
packages/core/src/ci-environment/services/gitlab.ts
packages/core/src/ci-environment/services/heroku.ts
packages/core/src/ci-environment/services/travis.ts
packages/core/src/ci-environment/types.ts
packages/core/src/config.ts
packages/core/src/upload.ts
packages/core/src/version.ts
packages/playwright/src/reporter.ts

- **feat: compatibility to granular GitHub Actions jobs retries**
- **refactor: remove "ciService" from config**

1203 allow to re upload a chunk of a build

---

package.json
packages/api-client/package.json
packages/browser/package.json
packages/cli/package.json
packages/core/package.json
packages/cypress/package.json
packages/cypress/src/test-types.ts
packages/gitlab/package.json
packages/playwright/package.json
packages/playwright/src/index.ts
packages/puppeteer/package.json
packages/util/package.json
packages/webdriverio/package.json
packages/webdriverio/tsconfig.json
packages/webdriverio/wdio.conf.ts
pnpm-lock.yaml
typedoc.json

Upgrade dependencies to fix potential CVE.

upgrade dependencies

---

package.json
packages/api-client/src/index.ts
packages/api-client/src/schema.ts
packages/core/src/upload.ts
packages/cypress/src/task.ts
packages/playwright/src/reporter.ts

- **feat: collect test report infos in cypress and playwright**
- **chore: fix canary command**

test report

---

packages/api-client/package.json
pnpm-lock.yaml

https://github.com/openapi-ts/openapi-typescript/issues/2032

fix: fix open-api-fetch version

---

.github/workflows/ci.yml
commitlint.config.mjs
package.json
packages/browser/src/global/stabilization.ts
pnpm-lock.yaml

Set "-webkit-font-smoothing" to "antialised" to reduce text-aliasing issues
BREAKING CHANGE: if not using "-webkit-font-smoothing: antialiased" you may experience differences on text after the update

fix(chromium): reduce text-aliasing issue

---

packages/cypress/package.json

feat(cypress): support Cypress v14

---

packages/storybook/docs/index.mdx
packages/storybook/package.json
packages/storybook/stories/Form.jsx
packages/storybook/stories/Form.stories.js
pnpm-lock.yaml

Confirm that the "play" function is executed before running screenshot.
See here: https://app.argos-ci.com/argos-ci/argos-javascript/builds/14974/145385256
Documentation.
Valid all before asking for a code review to `argos-ci/code` :
*Optional* : Feel free to explain your motivation, share useful information or a feature screenshot.

docs: clarify the Storybook play function behaviour

---

packages/browser/src/global/stabilization.ts

- **fix: fix image stabilization**
- **fix: fix image stabilization**

fix image stabilization

---

packages/browser/src/global/media.ts
packages/storybook/.storybook/main.ts
packages/storybook/.storybook/modes.ts
packages/storybook/.storybook/preview.ts
packages/storybook/package.json
packages/storybook/src/index.ts
packages/storybook/stories/Form.stories.js
packages/storybook/stories/Page.stories.js
packages/storybook/stories/button.css
pnpm-lock.yaml

Similar to chromatic.modes, it allows to capture screenshots on different viewports and themes and any global used in any plugin.

feat(storybook): support argos.modes

---

packages/cypress/cypress.config.cjs
packages/cypress/cypress/e2e/argosScreenshot.cy.ts
packages/cypress/src/shared.ts
packages/cypress/src/support.ts
packages/cypress/src/task.ts
packages/playwright/src/reporter.ts
packages/util/src/fs.ts
packages/util/src/index.ts
packages/webdriverio/package.json
packages/webdriverio/wdio.conf.ts
pnpm-lock.yaml

Cypress naming can change over time and be unreliable
BREAKING CHANGE: Screenshot taken with `@argos/cypress` will change of name after upgrade

fix(cypress): use Argos name as screenshot name

---

packages/browser/src/global/stabilization/plugins/loadImageSrcset.ts

fix(stabilization): bust with hash if possible

---

packages/core/src/ci-environment/git.test.ts
packages/core/src/ci-environment/git.ts
packages/core/src/ci-environment/services/bitrise.ts
packages/core/src/ci-environment/services/buildkite.ts
packages/core/src/ci-environment/services/circleci.ts
packages/core/src/ci-environment/services/git.ts
packages/core/src/ci-environment/services/github-actions.ts
packages/core/src/ci-environment/services/gitlab.ts
packages/core/src/ci-environment/services/travis.ts
packages/core/src/ci-environment/types.ts
packages/core/src/config.ts
packages/core/src/util/url.test.ts
packages/core/src/util/url.ts

Finally we will not use it now, but since the code is good and written, we commit it.

refactor: allow to get repository from CI

---

packages/core/src/auth.test.ts
packages/core/src/auth.ts
packages/core/src/config.ts

fix(github): fix tokenless auth

---

packages/core/src/ci-environment/git.ts

When a merge base is not found, it returns a status of 1 with no error.
In this case it's not a fatal error, just no merge-base found.

fix(git): fix merge base error

---

packages/cli/src/commands/upload.ts
packages/core/src/config.ts

fix(config): improve parallel validation
