- packages/core/src/api-client.ts
- packages/core/src/ci-environment/env-ci.ts
- packages/core/src/ci-environment/services/buildkite.ts
- packages/core/src/ci-environment/services/circleci.ts
- packages/core/src/ci-environment/services/github-actions.ts
- packages/core/src/ci-environment/services/heroku.ts
- packages/core/src/ci-environment/services/travis.ts
- packages/core/src/ci-environment/types.ts
- packages/core/src/config.ts
- packages/core/src/upload.ts
In this PR, we add a `prHeadCommit` sends from GitHub Actions.
Now `commit` is `$GITHUB_SHA` and we also send the `prHeadCommit` to be displayed in UI. 
https://github.com/argos-ci/argos/pull/944 must be merged first.
Closes #50
> feat(core): send prHeadCommit at build creation

- packages/core/src/ci-environment/index.ts
- packages/core/src/ci-environment/services/gitlab.ts
We were using env-ci package for GitLab, however, the information is not accurate. In a PR it does not give the branch but the PR target branch.
[`env-ci`](https://github.com/semantic-release/env-ci/blob/7fb0980197ad55ce274370de0ee9440da0ec86f2/services/gitlab.js#L20-L22)
I fixed it by adding a custom service. Also on GitLab we don't have to set repo, pr, etc... all of that is for GitHub. To support that, it is part of supporting tokenless.
> feat(gitlab): support gitlab ci

- packages/cypress/src/support.ts
Screenshot command fails when trying to read `package.json`. If bundler is loading via type `module` then `require.resolve` will fail and should fallback to hard-coded string path to `node_modules` like in `injectArgos`.
`bug`
Valid all before asking for a code review to `argos-ci/code` :
- [n/a] I have added tests if needed
Optional checks:
- [n/a] My changes requires a change to the documentation
- [n/a] I have updated the documentation accordingly
> Fix Cypress `require.resolve` issue

- packages/core/src/ci-environment/index.ts
- packages/core/src/ci-environment/services/bitrise.ts
- packages/core/src/ci-environment/services/git.ts
In this PR, I have added the support of Bitrise CI.
- semantic-release [env-ci implementation](https://github.com/semantic-release/env-ci/tree/6919ed838a004a4e7b3327da7842bc140e7e3a10)
- Bitrise [environment variables doc](https://devcenter.bitrise.io/en/references/available-environment-variables.html)
> feat: support bitrise ci

- packages/playwright/src/reporter.ts
Handle nested directories while copying files.
> fix(playwright): fix copyFile error

- packages/playwright/docs/index.mdx
- packages/puppeteer/docs/index.mdx
The default value of `fullPage` is surcharged by `argosScreenshot`. It's important to make it explicit for users coming from `screenshot` or `toHaveScreenshot`.
> docs: precise `fullPage` behaviour

- packages/cypress/src/support.ts
- packages/cypress/src/task.ts
- feat(cypress): track retries
- fix(cypress): rename screenshots with retries
> 111 attempts in the name of the screenshot on cypress sdk

- packages/playwright/src/reporter.ts
- packages/webdriverio/package.json
- pnpm-lock.yaml
Traces are now attached to all screenshots not only failure screenshots.
It allows to have enhanced visual testing debugging for visual
differences.
> feat: enable traces for non-failure screenshots

- packages/playwright/docs/index.mdx
- packages/playwright/src/index.ts
Also document how to handle CSP issues.
> feat: expose `getCSPScriptHash` in `@argos-ci/playwright`

- packages/browser/src/viewport.ts
- packages/playwright/src/index.ts
- packages/puppeteer/src/index.ts
**Bug Description**  
The `viewports` option in the Playwright integration caused flaky screenshots because Argos was capturing them before the viewport fully resized. This led to [flaky tests](https://app.argos-ci.com/defacto/front-onboarding/builds/3807/110435367).
**Expected Behavior**  
The viewport should resize to the specified dimensions before any screenshot is taken.
**Fix Explanation**  
The Playwright integration has been updated to wait for the viewport to fully resize before capturing screenshots, resolving the issue of flaky tests.
> feat(playwright): wait for viewport resize

- packages/api-client/package.json
- packages/api-client/src/debug.ts
- packages/api-client/src/index.ts
- packages/core/src/finalize.ts
- packages/core/src/upload.ts
- packages/webdriverio/package.json
- pnpm-lock.yaml
Added the message from detailed object to the error message. This will enable customers to understand what the actual error was. 
Select the correct labels: `bug`, `enhancement` or `documentation`.
Valid all before asking for a code review to `argos-ci/code` :
Optional checks:
*Optional* : Feel free to explain your motivation, share useful information or a feature screenshot.
> Enhance error thrown by api client

- packages/browser/src/global/stabilization.ts
Altering IFRAME element causes playwright to re-render contents while taking screenshot which may result in unstable screenshots.
bug
Valid all before asking for a code review to `argos-ci/code` :
- [ ] The commits message follows the [Conventional Commits' policy](https://www.conventionalcommits.org/)
Optional checks:
*Optional* : Feel free to explain your motivation, share useful information or a feature screenshot.
> fix: don't modify IFRAME to avoid reloads

- packages/api-client/tsup.config.ts
- packages/browser/src/global/index.ts
- packages/browser/src/global/stabilization.ts
- packages/browser/src/index.ts
- packages/cli/tsup.config.ts
- packages/core/tsup.config.ts
- packages/cypress/docs/index.mdx
- packages/cypress/src/support.ts
- packages/cypress/tsup.config.ts
- packages/gitlab/tsup.config.ts
- packages/playwright/docs/index.mdx
- packages/playwright/src/screenshot.ts
- packages/playwright/tsup.config.ts
- packages/puppeteer/docs/index.mdx
- packages/puppeteer/src/index.ts
- packages/puppeteer/tsup.config.ts
- packages/storybook/src/index.ts
- packages/storybook/tsup.config.ts
- packages/util/tsup.config.ts
- packages/webdriverio/tsup.config.ts
- **feat: allow to customization stabilization options**
- **fix(storybook): disable aria-busy stabilization by default**
- **refactor: rename stability check method**
- **feat(cypress): improve stability debugging**
> custom stabilization

- packages/storybook/docs/index.mdx
- packages/storybook/src/index.ts
- **fix: detect library version only from "@storybook/test-runner"**
- **docs: document storybook SDK**
> storybook docs

- packages/api-client/src/schema.ts
- packages/core/src/config.ts
- packages/core/src/upload.ts
- packages/cypress/docs/index.mdx
- packages/cypress/src/task.ts
- packages/playwright/docs/index.mdx
- packages/playwright/src/reporter.ts
- packages/playwright/src/screenshot.ts
- packages/util/src/metadata.ts
Preview URL allow to set a custom URL to override the default URL
and allow to navigate easily to a live environment deployed
remotely instead of having a "localhost" URL.
> feat: support preview URL

- packages/browser/src/global/stabilization.ts
- packages/cypress/docs/index.mdx
- packages/playwright/docs/index.mdx
- packages/puppeteer/docs/index.mdx
When the viewport is changed, the browser fails to re-calculate the
proper image size. With that new stabilization we ensure images are
stable with `viewports` option.
> feat: stabilize image sizes

- packages/browser/src/global/stabilization/plugins/roundImageSize.ts
Use `offsetX` instead of `getBoundingClientRect()`
> fix(stabilization): fix stabilization on transformed images

- packages/browser/src/global/stabilization/plugins/waitForAriaBusy.ts
- packages/playwright/src/screenshot.ts
- **fix: remove unrelevant code to load images in `waitForAriaBusy`**
- **fix(playwright): properly return stabilization failure reasons**
- **chore(playwright): change the order of operations before taking the screenshot**
> playwright stabilization reasons

- packages/browser/src/global/stabilization/plugins/loadImageSrcset.ts
Override previously set URL hashes for busting images in srcsets.
Follow-up to #202 and fixes #201.
> fix(stabilization): override image busting hash

- packages/browser/src/global/stabilization/index.ts
- packages/browser/src/global/stabilization/plugins/loadImageSrcset.ts
- packages/cypress/src/support.ts
- packages/playwright/src/screenshot.ts
- packages/puppeteer/src/index.ts
`loadImageSrcset` plugin is only useful if the user has viewports. If not it's better to disable it because when Playwright takes a fullpage screenshot it triggers a resize event.
> Disable `loadImageSrcset` stabilization plugin if the user is not using the `viewports` option

- packages/storybook/src/vitest-plugin.ts
Now use `body` instead of a custom element to be more reliable
> fix(storybook): fix `fitToContent` behaviour

- packages/storybook/src/test-runner.ts
- packages/storybook/src/utils/screenshot.ts
- packages/storybook/src/vitest-plugin.ts
`waitForPageReady` was called also after taking the screenshot causing instabilities
> fix(storybook): fix timeout and instability with test runner
